### ISSUE TITLE
warning in google devel console

### ISSUE THREAD

**Issue by teneon** [ghostdevv/svelte-turnstile#32]
Hi there,

If i include in sveltekit +page.svelte something like this:
```

<script>
    import { Turnstile } from 'svelte-turnstile';
</script>

<Turnstile siteKey="1x00000000000000000000AA" />
```

In the chrome devel console i get this warning:

auto/:1 The resource https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/cmg/1/KyD54HPQyYTTGsyPe287%2B%2FhqCpUx21vUQSbaREjxy9c%3D was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

Any ideas if it is something i can solve on my end ?

Kind regards,
Jim

**Comment by ghostdevv** [comment]
Hey, that's a normal warning to see with Turnstile at the moment. We can't fix it on the svelte-turnstile end unfortunately - regardless you can safely ignore it!
